const inquirer = require("inquirer")
const intern = require("./lib/Intern.js")
const manager = require("./lib/Manager.js")
const employee = requre("./lib/Employee.js")
const engineer = require("./lib/Engineer.js")
